app:
  name: FinOps Guard
  timezone: America/New_York

schedule:
  daily_run_hour_utc: 10
  weekly_report_day: monday
  weekly_report_hour_utc: 11

thresholds:
  anomaly_zscore: 1.5
  min_absolute_delta_usd: 1
  min_history_points: 5
  baseline_days: 7
  trend_days: 7
  trend_min_increase_pct: 20
  trend_min_absolute_delta_usd: 1
  

reporting:
  teams_channel: finops-ops
  email_distribution:
    - finops@company.com
    - platform@company.com

aws:
  lookback_days: 90
  required_tags:
    - owner
    - env
    - cost_center
